spring:
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/spring_shopping
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${USERNAME}
    password: ${PASSWORD}

security:
  jwt:
    token:
      secret-key: ${SECRET_KEY}
      expire-time: ${EXPIRE}
